### ISSUE TITLE
Incomplete versions of `p_from_z` and `z_from_p`

### ISSUE THREAD

**Issue by efiring** [TEOS-10/GSW-C#31]
See https://github.com/TEOS-10/GSW-Python/issues/48.
Are there any strenuous objections to adding the geo_strf_dyn_height and sea_surface_geopotential arguments to the `p_from_z` function and its inverse?  They would be required arguments, so any present code using the old signatures would have to be updated.  I suspect that in practice this is just the R version. @dankelley?
Although the arguments would be required in C, I would make them optional in Python.

**Comment by DocOtak** [comment]
Sounds good to me. 

In whatever docs there are which accompany this, be sure to note that setting both geo_strf_dyn_height and sea_surface_geopotential arguments to 0 would replicate the default and current behavior.

**Comment by ocefpaf** [comment]
Looks like this one as addressed in https://github.com/TEOS-10/GSW-C/pull/32, right? Closing this but please reopen if I got it wrong.
