### ISSUE TITLE
Specific volume second derivative SA P mistake (from Matlab)

### ISSUE THREAD

**Issue by richardsc** [TEOS-10/GSW-C#52]
See https://github.com/TEOS-10/GSW-Matlab/commit/38c9635d6fd93e74c2648e4ee23cec49c1f58530 in the Matlab repo. This should be updated through downstream repos.

**Comment by ocefpaf** [comment]
@richardsc do you mind taking a look at #53?

The updated code and test dataset fixed most of the failing tests but `c_from_sp`, `sp_from_c` and `geo_strf_dyn_height` are not passing. I don't expected `geo_strf_dyn_height` to pass with the new values but they are not passing with the [patched ones either](https://github.com/TEOS-10/GSW-C/blob/b5ecb2a9d4adbe123cfe7b098b2288a2db82e8f5/make_data_from_mat.py#L334-L336). @efiring do you have any clues for us there?

I could not find any more code differences in https://github.com/TEOS-10/GSW-Matlab/pull/15/files that could explain the `c_from_sp` and `sp_from_c` failures. But I may be missing something, that diff is massive!
