### ISSUE TITLE
gsw_melting_ice_equilibrium_sa_ct_ratio == gsw_melting_seaice_equilibrium_sa_ct_ratio

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-C#6]
These functions (at https://github.com/TEOS-10/GSW-C/blob/master/gsw_oceanographic_toolbox.c#L5356 and https://github.com/TEOS-10/GSW-C/blob/master/gsw_oceanographic_toolbox.c#L5401) are the same, apart from a comment line and a space in one code line.  Also, the matlab webpages (at http://www.teos-10.org/pubs/gsw/html/gsw_melting_ice_equilibrium_SA_CT_ratio.html and http://www.teos-10.org/pubs/gsw/html/gsw_melting_seaice_equilibrium_SA_CT_ratio.html) appear to be the same (e.g. the check values seem to match, by eye).

I think the C is just inheriting the twinning from the matlab. I assume the Fortran has the same issue. I've not checked on python, haskell, etc.

Dan.

**Comment by hylandg** [comment]
This should be the same for Fortran and all other languages. The difference between ice and seaice is that seaice will have some salinity, and as noted in the comments of `gsw_melting_seaice_equilibrium_sa_ct_ratio` ...
```Fortran
!  Note that the output of this function, dSA/dCT is independent of the 
!  sea ice salinity, SA_seaice.  That is, the output applies equally to  
!  pure ice Ih and to sea ice with seaice salinity, SA_seaice.  This result 
!  is proven in the manuscript, McDougall et al. (2013).  
```

So worth noting, but nothing to worry about.
