### ISSUE TITLE
Meson build file?

### ISSUE THREAD

**Issue by peter-urban** [TEOS-10/GSW-C#72]
I created a [meson.build](https://github.com/peter-urban/GSW-C-meson/blob/master/meson.build) file (with tests) to more easily integrate this project with my existing projects.
I was wondering if you want to add this to the main project? (It can live next to the Makefile)
If so, I can work on a clean PR.

If not: feel free to reject this issue. It is no problem maintain this as separate [fork](https://github.com/peter-urban/GSW-C-meson).

**Comment by ocefpaf** [comment]
I'll defer to Eric but, IMO, I welcomed a meson build. We might as well use it in the future to build the Python extension too. My only concern is with the increased complexity. I would remove the Makefile in the future if all we need is the meson.build.

**Comment by peter-urban** [comment]
> Just out of curiosity, what are you building?

[themachinethatgoesping](https://github.com/themachinethatgoesping) It's is a multibeam and singlebeam python processing library (written in c++). GSW-C is to be used for absorption computation.

> We might as well use it in the future to build the Python extension too.

I am happy to contribute if you want to move in this direction . I use meson with [meson-python](https://meson-python.readthedocs.io/en/latest/) as a build backend for my python extensions. Though I don't have experience with ufunc etc. Anyways, that's an issue for [GSW-Python](https://github.com/TEOS-10/GSW-Python) once this issue is discussed ;-)

**Comment by efiring** [comment]
I would welcome the meson build for this project, as well as the possibility of your participation in additional projects.

**Comment by peter-urban** [comment]
Ok, good to know! I'll prepare a PR when I find the time. (It may take a while, but it'll happen)

**Comment by peter-urban** [comment]
Thanks for merging. Now I can directly use the original repo in my project :-)
