### ISSUE TITLE
update functions to more closely match matlab?

### ISSUE THREAD

**Issue by efiring** [TEOS-10/GSW-C#9]
I am working on an automated wrapping of the C code in Python, in the course of which I find some C functions that could be updated in various ways to better match the matlab, and some functions that I suspect are left over from earlier versions; they have no matching m-files.  The functions I have encountered so far are:

In C only? Obsolete? Delete?
- ct_freezing_exact
- pt0_cold_ice_poly
- pt_from_pot_enthalpy_ice_poly_dh
- t_freezing_exact

Extra (optional) arguments in matlab:
- pot_enthalpy_ice_freezing mismatch: ('sa', 'p'), ('SA', 'p', 'saturation_fraction')
- z_from_p mismatch: ('p', 'lat'), ('p', 'lat', 'geo_strf_dyn_height', 'sea_surface_geopotental')

I could make PRs for such changes to bring the C closer to the current matlab; would they be welcome? (I would probably not do anything about optional output arguments; in the one case that comes to mind, it is a nearly-useless validity flag that can be obtained separately.)  The method to be used for handling optional arguments is open to discussion.  Options include using separate functions for each signature, or using a single variadic signature. 

My priority is in the basic functionality, especially the simple scalar functions; for some of the more complex functions, including most that operate on profiles, I think that re-implementation in Python will be adequate for my purposes.

**Comment by PaulMBarker** [comment]
the codes that appear in C only are subroutines that probably are at the end of one of the functions.
eg. pt_from_pot_enthalpy_ice_poly_dh is a subroutine in pt_from_pot_enthalpy_ice

**Comment by PaulMBarker** [comment]
we added the extra inputs to z_from_p in a more recent version of the programme, adding dynamic height improves the accuracy of the calculation.

**Comment by efiring** [comment]
@PaulMBarker Thanks for the info.  I completely forgot to check for subroutines.

**Comment by hylandg** [comment]
The 2 temperature freezing functions
- ct_freezing_exact
- t_freezing_exact

are Fortran specific (as per https://github.com/TEOS-10/GSW-Fortran/issues/4) and within the C-code could be renamed to

- ct_freezing
- t_freezing

without loss of functionality.

**Comment by efiring** [comment]
Closed by #10.
